- packages/sdk/src/models/issue.ts
- packages/sdk/src/models/label.ts
- packages/sdk/src/models/team.ts
Originally I was using TypeScript's baseDir importing feature, but that doesn't work too well with lerna bootstrap so I'm scrapping that for less magical paths.
> Fix root imports that fail when linked

- .changeset/grumpy-goats-heal.md
- packages/import/src/importers/trelloJson/TrelloJsonImporter.ts
Trello labels can be created with no name, but all Linear issue labels must have a name. Set a default name for labels without one.
Fixes this issue: https://github.com/linear/linear-import/issues/53
> fix(import): create name for Trello labels with no name

- .changeset/ten-mayflies-join.md
- packages/import/package.json
- packages/import/src/importIssues.ts
- packages/import/src/importers/asanaCsv/AsanaCsvImporter.ts
- packages/import/src/types.ts
- yarn.lock
* Importing `date-fns`
* Adding `dueDate` to `Issue` type
* Collecting Asana due date from the csv
Fixes: https://github.com/linear/linear-import/issues/48
> feat(import): adding due dates to Asana importer

- .github/workflows/dependencies.yaml
- .github/workflows/schema.yaml
- packages/sdk/scripts/generate-dependencies-changeset.ts
- packages/sdk/scripts/generate-schema-changeset.ts
Fixes the changeset getting overwritten if the version package PR has not been merged before another schema PR is merged into master
> fix(actions): unique generated changeset filenames

- .changeset/real-camels-remain.md
- packages/import/src/importers/trelloJson/TrelloJsonImporter.ts
- packages/import/src/importers/trelloJson/index.ts
This PR adds the ability to discard unarchived cards from archived lists (resolves #92). The existing _"Would you like to discard the archived cards?"_ question is followed by a new _"Would you like to discard the (possibly unarchived) cards within archived lists?"_ question.
In the for loop on `data.cards` the flag (`discardArchivedLists`) will be used to determine if a is-list-archived check is necessary. If so the `.find` method is used. Performing this check is not the most efficient way to include/exclude the card from the export but it is the least convoluted due to the logic residing in a single if statement. The following would be more performant:
```typescript
const listIdsToIgnore: string[] = this.discardArchivedLists
? (data.lists as TrelloList[])
.filter((list) => list.closed) …
```
> Added option to discard archived lists with the Trello JSON file import.

- .changeset/green-avocados-shout.md
- packages/import/README.md
- packages/import/src/cli.ts
- packages/import/src/importIssues.ts
- packages/import/src/importers/linearCsv/LinearCsvImporter.ts
- packages/import/src/importers/linearCsv/index.ts
- packages/import/src/types.ts
Transferring over this PR that wasn't merged from the older import repo: https://github.com/linear/linear-import/pull/32
Added additional functionality to it to infer status types and transfer custom statuses.
Closes: https://github.com/linear/linear/issues/80
> feat(import): transferring Linear to Linear CSV importer from old repo

- .changeset/tender-trains-rest.md
- package.json
- packages/sdk/src/index.ts
- tsconfig.check.json
- yarn.lock
**Changes:**
- add `tsc` check during `build` script
- add `@types/ws` to fix `tsc`
- add reference to typescript `lib.dom`
_Might_ fix https://github.com/linear/linear/issues/95#issuecomment-826904831
With commit https://github.com/linear/linear/pull/101/commits/cda49661616b909626b559845706264583867dcc
> fix(build): add tsc check and fix types

- .changeset/_generated_schema_19082443.md
- .changeset/_generated_schema_2958400.md
- .changeset/_generated_schema_35990194.md
- .changeset/_generated_schema_46759633.md
- .changeset/_generated_schema_49620367.md
- .changeset/_generated_schema_60960090.md
- .github/workflows/schema.yaml
- packages/codegen-sdk/src/constants.ts
- packages/codegen-sdk/src/plugin.ts
- packages/codegen-sdk/src/print-connection.ts
- packages/codegen-sdk/src/print-model.ts
- packages/codegen-sdk/src/print-operation.ts
- packages/sdk/src/_generated_documents.graphql
- packages/sdk/src/_generated_documents.ts
- packages/sdk/src/_generated_sdk.ts
- packages/sdk/src/_tests/_generated.test.ts
- packages/sdk/src/schema.graphql
- packages/sdk/src/schema.json
- pass optional variables to mutations
- no need for eslint ignore unused variables in generated sdk now 🥳
- use async await syntax in generated sdk
- cleanup internal Response type name
- fix schema action test script rename
- update schema
> feat(sdk): use optional mutation variables and update schema

- .changeset/shiny-falcons-return.md
- packages/import/src/importers/jiraCsv/JiraCsvImporter.ts
The variable 'organizationName' was kind of misleading because the org name can actually be different from the Jira (Atlassian) site name, that is needed here
[jira site name explanation](https://confluence.atlassian.com/cloudkb/changing-the-cloud-instance-url-address-or-migrating-to-a-new-cloud-instance-691011835.html)
*game changing fix
> Fix doc comment and rename variable in JiraCsvImporter.ts

- .changeset/funny-spies-sell.md
- packages/import/src/importers/trelloJson/TrelloJsonImporter.ts
* Adding Trello checklists to imported issue descriptions
* Parsing through actions in the Trello JSON export to find created comments and attaching them to issues
Fixes #121
> feat(import): adding checklists and comments to Trello import

- .changeset/nine-shirts-cheer.md
- packages/import/src/importIssues.ts
- packages/import/src/importers/trelloJson/TrelloJsonImporter.ts
* Add the list of Trello attachments as a list within the description of an imported issue
* Looks like some auto formatting came along for the ride
>  feat(import): add attachments to issue description for Trello imports

- packages/codegen-doc/src/context-visitor.ts
- packages/codegen-doc/src/fragment-visitor.ts
- packages/codegen-doc/src/fragment.ts
- packages/codegen-doc/src/object.ts
- packages/codegen-doc/src/types.ts
- packages/codegen-sdk/src/model-visitor.ts
- packages/sdk/src/_generated_documents.graphql
- packages/sdk/src/_generated_documents.ts
- packages/sdk/src/_generated_sdk.ts
Adds support for interfaces.
1. ContextVisitor picks them up
2. Codegen-doc generates fragments for them
3. Codegen-sdk also picks them up (which in turn generates classes for them)
This had the side-effect of adding the Node interface (which was our only used interface).
> Add support for interfaces

- .changeset/_generated_schema_2268650.md
- packages/codegen-doc/package.json
- packages/codegen-doc/src/context-visitor.ts
- packages/codegen-doc/src/fragment-visitor.ts
- packages/codegen-doc/src/types.ts
- packages/codegen-sdk/package.json
- packages/codegen-sdk/src/model-visitor.ts
- packages/codegen-sdk/src/parse-operation.ts
- packages/codegen-sdk/src/print-connection.ts
- packages/codegen-sdk/src/print-operation.ts
- packages/codegen-sdk/src/types.ts
- packages/codegen-test/package.json
- packages/codegen-test/src/print-test.ts
- packages/import/package.json
- packages/sdk/package.json
- packages/sdk/src/_generated_documents.graphql
- packages/sdk/src/_generated_documents.ts
- packages/sdk/src/_generated_sdk.ts
- packages/sdk/src/_tests/_generated.test.ts
- packages/sdk/src/schema.graphql
- packages/sdk/src/schema.json
Updates:
- include `__typename` in all fragments.
- add fragments for each interface implementation to the generated graphql documents
- the sdk now returns a union type (in place of interfaces) and the objects are instantiated correctly as the implementing classes based on their `__typename`. It falls back to the "interface" class for unknown typenames.
- the tests are updated to fix types for interface return types.
It's easiest to review by looking at the updated output first and then at the implementation.
> feat(sdk): fix interface support

- .changeset/dry-poets-promise.md
- packages/import/src/importIssues.ts
Issues are not always imported to team's backlog but to corresponding workflow statuses, so the current message and the link are misleading.
> fix: improve import cli message

- .changeset/strong-pens-film.md
- packages/codegen-doc/package.json
- packages/codegen-doc/rollup.config.js
- packages/codegen-sdk/package.json
- packages/codegen-sdk/rollup.config.js
- packages/codegen-test/package.json
- packages/codegen-test/rollup.config.js
- packages/import/package.json
- packages/import/rollup.config.js
- packages/import/src/importIssues.ts
- packages/sdk/package.json
- packages/sdk/rollup.config.js
- yarn.lock
Removes deprecated rollup plugin `rollup-plugin-size-snapshot` that does not support Node 18+.
The plugin was used to compute the size of the generated SDK. It looks preferable to remove its usage rather than prevent the SDK from building on newer versions of Node.
We should be able to publish an update of the SDK after this is merged.
> fix: remove deprecated rollup plugin

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- .github/workflows/schema.yaml
The purpose of this PR is to fix Github Actions failures on workflows when started by dependabot. 
https://github.com/linear/linear/actions/runs/3866812606/jobs/6614089466
The step `Compare schema for changes` which relies on `kamilkisiela/graphql-inspector@master` fails with:
```
Error: Resource not accessible by integration
```
The rationale behind the write permission on `checks` scope is that this integration will update the checks of the PR its running on.
> fix: declare Github Action permissions in workflow

- package.json
- packages/codegen-doc/package.json
- packages/codegen-sdk/package.json
- tsconfig.json
- yarn.lock
The purpose of this PR is to solve build issues that occur when trying to update dependencies as part of the `dependencies` workflow.
https://github.com/linear/linear/actions/runs/3878889472/jobs/6615503188
The `dependencies` workflow is a daily job that attempts to update the dependencies in order to consume minor and patch updates. Two main changes occur here:
Typescript is declared as `^4.0.5`. When running, the job was updating typescript to 4.9.x. It turns out that plenty of graphql dependencies we use will not compile properly with typescript 4.8 and above. In order to avoid a larger update now, typescript is pinned to `~4.7.4`, the last minor version to properly compile.
This dependency is implicitly required by `graphql-faker` and `graphql-voyager`, both of which are stale …
> fix: pin some dependencies to fix Github dependencies workflow

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- .github/workflows/schema.yaml
#239 introduced granular permissions in workflows in order to fix dependabot PRs. It worked, builds are now green, but the permissions used are too restrictive: the workflows also need the ability to open/update PRs and push code as part of the release process.
> fix: allow Github Actions to open PRs and push code

- .changeset/short-keys-enjoy.md
- packages/sdk/src/_tests/bundle.test.ts
Internal change #13208 broke this test. Not sure if we need this test to be _that_ specific when it comes to the error message, will look into revamping it as part of a larger tests fixing effort (See PUB-13)
> fix: update auth error message used by tests

- .changeset/_generated_schema_29592340.md
- .changeset/_generated_schema_97502883.md
- .changeset/stale-zebras-brush.md
- packages/codegen-doc/src/fragment.ts
- packages/codegen-sdk/src/model-visitor.ts
- packages/sdk/src/_generated_documents.graphql
- packages/sdk/src/_generated_documents.ts
- packages/sdk/src/_generated_sdk.ts
- packages/sdk/src/schema.graphql
- packages/sdk/src/schema.json
The skip comments, designated by `[Internal]` or `[Alpha]` were only meant to skip specific fields. But it turns out we have taken the habit to use on whole objects as well.
This PR adds support for skip comments on objects in additions to fields
> feat: support skipComment for objects

- .changeset/wicked-cups-report.md
- packages/codegen-doc/rollup.config.js
- packages/codegen-sdk/rollup.config.js
- packages/codegen-test/rollup.config.js
- packages/import/rollup.config.js
- packages/sdk/rollup.config.js
This PR disables all minify plugins (terser and gzip) in dev mode as they make it hard to work with a debugger.
> feat: do not minify plugins in dev mode

- .changeset/_generated_schema_10584077.md
- .changeset/_generated_schema_77603279.md
- .changeset/old-moons-tie.md
- packages/sdk/codegen.test.yml
- packages/sdk/src/_generated_documents.graphql
- packages/sdk/src/_generated_documents.ts
- packages/sdk/src/_generated_sdk.ts
- packages/sdk/src/_tests/_generated.test.ts
- packages/sdk/src/schema.graphql
- packages/sdk/src/schema.json
Adds configuration to skip some comment annotated fields during test generation. This is the same configuration that is used when generating the SDK code.
```
config:
skipComments:
- "[Internal]"
- "[INTERNAL]"
- "[ALPHA]"
```
> fix: do not generate tests for skip comments

- .changeset/serious-kiwis-wink.md
- packages/sdk/src/_tests/LinearWebhooks.test.ts
- packages/sdk/src/index.ts
- packages/sdk/src/webhooks.ts
This PR introduces a new `Webhooks` aimed at dealing with Linear Webhooks.
Its first method is a helper to verify the HMAC signatures. See https://developers.linear.app/docs/graphql/webhooks#securing-webhooks for documentation
> feat: add LinearWebhooks class to help work with Linear webhooks

- .changeset/lovely-goats-deliver.md
- .eslintrc.js
- packages/import/bin/linear-import.js
Adds a CLI argument `--version` to print out current version number of the CLI importer, for support purposes.
> Add `--version` argument to CLI importer

- .changeset/late-pumas-whisper.md
- packages/codegen-doc/src/fragment-visitor.ts
- packages/codegen-doc/src/fragment.ts
- packages/codegen-doc/src/object.ts
- packages/codegen-sdk/src/constants.ts
- packages/codegen-sdk/src/parse-operation.ts
- packages/codegen-sdk/src/print-connection.ts
- packages/codegen-sdk/src/print-model.ts
- packages/codegen-sdk/src/print-operation.ts
- packages/codegen-sdk/src/print-sdk.ts
The `schema` Github action is currently breaking, preventing future SDK releases. The reason for failure is 
```
GraphQLDocumentError: Unknown fragment "ExternalUser".
```
It comes from the fact that we have marked `ExternalUser` entity as [ALPHA]. Some operations are not annotated with the same comment though. Also, the schema contains one type related to `ExternalUser`: `ExternalUserConnection`, for which it's not possible to write an annotation.
This PR intends to skip generating objects that are related to a model being marked as skipped:
- The Connection model linked to the model
- Queries that are meant to return the model
> feat: check if Connection type is valid or not

- .changeset/purple-lies-warn.md
- packages/sdk/scripts/generate-schema-changeset.ts
Currently, the `schema` action will generate a changeset that will always result in a `minor` sdk bump, regardless of whether the schema changes are breaking or not. (Example: #306)
If there is a breaking API change, than it will result in an SDK breaking change, which means we should bump sdk package accordingly, by bumping to the highest criticality included in the changeset.
> feat: follow semver for schema related SDK bumps

- packages/import/README.md
Change `-g` by `--location=global` in readme file
> Fix: deprecated -g in npm cli

- .changeset/strange-dryers-sort.md
- packages/import/package.json
- yarn.lock
Chalk was recently upgraded from 4.x to 5.x by dependabot in #339.
As Chalk 5.x is now a [pure](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) ESM package, it cannot be used in a CommonJS project.
```
var chalk = require('chalk');
^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/guillaumelachaud/.nvm/versions/node/v18.12.1/lib/node_modules/@linear/import/node_modules/chalk/source/index.js from /Users/guillaumelachaud/.nvm/versions/node/v18.12.1/lib/node_modules/@linear/import/dist/cli.js not supported.
Instead change the require of index.js in /Users/guillaumelachaud/.nvm/versions/node/v18.12.1/lib/node_modules/@linear/import/dist/cli.js to a dynamic import() which is available in all CommonJS modules.
at Object.<anonymous> …
```
> chore: downgrade chalk to 4.x

- examples/nextjs-file-upload/README.md
create-next-app rejects the current URL, but using master works.
> chore: Fix example clone URL

- .changeset/mighty-vans-marry.md
- packages/import/src/importIssues.ts
The CLI importer currently doesn't support workspace-level or group labels. If any label in the import set conflicts with one of these, the importer crashes. This PR adds support for these:
- Pull list of workspace-level labels alongside team-level labels to check for potential conflict
- Check if existing labels are label groups. In the event of a match, we cannot use the group as a leaf label. Instead of picking the first label of the group, we default to renaming the label to `label (imported)`. This is inline with the behavior of the in-app importers.
There are no unit tests on this package. A sample CSV file is provided
[test_20230824_031624.csv](https://github.com/linear/linear/files/12425206/test_20230824_031624.csv)
> feat: add support for workspace-level labels and label groups

- .github/workflows/release.yaml
The `release` GitHub action is now failing:
```
Error: GitHub Actions is not permitted to create or approve pull requests.
at /home/runner/work/_actions/changesets/action/master/dist/index.js:718:926
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Object.m [as runVersion] (/home/runner/work/_actions/changesets/action/master/dist/index.js:1058:5104)
at async /home/runner/work/_actions/changesets/action/master/dist/index.js:1060:2297 {
```
Adding explicit permissions for more scope as the new GITHUB_TOKEN seems to be less permissive. Unfortunately, there is no word about permissions in the official [documentation](https://github.com/changesets/action) so there might be a bit of trial and error.
> fix: explicit permissions for more GA scopes

- .changeset/mean-pugs-appear.md
- packages/sdk/codegen.doc.yml
- packages/sdk/codegen.sdk.yml
- packages/sdk/codegen.test.yml
The SDK currently cannot be upgraded to the latest schema. It builds correctly, but the tests fail when trying query a user's notifications with the following error:
```
There can be only one fragment named "ActorBot".
```
This is happening because we have introduced `ActorBot` as a new type for a field on a type that's an implementation of an interface (Notification):
<details>
<summary>Notification Fragment</summary>
```graphql
fragment Notification on Notification {
__typename
type
botActor {
...ActorBot
}
updatedAt
emailedAt
readAt
unsnoozedAt
archivedAt
createdAt
snoozedUntilAt
id
actor {
id
}
user {
id
}
... on IssueNotification {
...IssueNotification.  <-- This one also has an ActorBot fragment
}
... on OauthClientApprovalNotification {
...OauthClientApprovalNotification <-- This …
```
> fix: use dedupeFragments with all codegen plugins

- .github/workflows/dependencies.yaml
Follow-up on #370. Also bumping version here in the action itself.
> fix: node-version bump to 18

- package.json
- yarn.lock
The `graphql-faker` package has been revived after 2 years without updates. Unfortunately, the 2.0.0 release has not been done properly and the package doesn't install. 
This PR intends to pin `graphql-faker` to `2.0.0-rc-25`  until https://github.com/graphql-kit/graphql-faker/issues/196 is resolved in order to fix the `dependencies` GH job.
> chore: pin graphql-faker to rc.25

- .changeset/silly-bulldogs-know.md
- .github/workflows/build.yaml
- .github/workflows/release.yaml
- .github/workflows/schema.yaml
- packages/sdk/src/_tests/_generated.test.ts
- packages/sdk/src/_tests/_mock.ts
- packages/sdk/src/_tests/test-client.ts
- yarn.lock
This PR fixes the `dependencies` [job](https://github.com/linear/linear/actions/runs/6450797116) that was timing out after 6 hours. The problem was in the tests, where `jest` failed to gracefully exit at the end of the test suite:
```
Time:        31.033 s
Ran all test suites.
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```
After a lot of trial and error (#389), I found the root cause: when running on Node 18.18.x, `execa` fails to properly kill the `npx` process that's used to spawn the fake graphql server used in tests. This keeps an handle open and prevents jest from exiting. The fix is to not use …
> Fix execa not killing child process properly

- .github/workflows/dependencies.yaml
Following #390, the `dependencies` job now builds and tests successfully! It now fails at the last step, when trying to create a PR:
```
Pushing pull request branch to 'origin/dependencies'
/usr/bin/git push --force-with-lease origin HEAD:refs/heads/dependencies
remote: Permission to linear/linear.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/linear/linear/': The requested URL returned error: 403
Error: The process '/usr/bin/git' failed with exit code 128
```
This PR adds the same permissions that are being used in other jobs.
> chore: add explicit permissions to `dependencies` job

- .changeset/sixty-geckos-promise.md
- packages/sdk/codegen.sdk.yml
- packages/sdk/naming-override/index.js
This PR introduces a hack relying on `graphql-coden`'s `typescript` plugin's option to override naming convention for different types. This allows to generate a valid `_generated_document.ts` despite the schema containing two queries that only differ by their case
From @smcgivern:
> We want to replace the `ProjectMilestone(s)?` query with
`projectMilestone(s)?`. To do this, we'll have a period where both
queries are in our API schema, which generates duplicate type names and
fails to build.
> As a hack, to work around this, we can simply append a counter to those
known-duplicate type names when we encounter them for the (N > 0)-th
time, and so let the SDK build. The types are identical otherwise so
there's no functional difference, just a bit of noise in the generated
output.
> Workaround to handle schema with duplicate queries

- .changeset/selfish-carrots-remember.md
- packages/import/src/importers/trelloJson/TrelloJsonImporter.ts
> fix: memberCreator does not exist for comment action in Trello import

- .changeset/stale-trains-walk.md
- packages/import/src/importIssues.ts
Fixes two issues related to Issue labels:
- paginates over the list of existing workspace and team labels to ensure we fetch them all
- Some services produce CSV files with duplicate label ids on a single issue. This PR also dedupes label IDs at the issue level.
> fix: support labels pagination and duplicate labels

- .changeset/quick-vans-compare.md
- packages/codegen-doc/src/constants.ts
- packages/codegen-doc/src/print-operation.ts
- packages/codegen-doc/src/query.ts
- packages/sdk/src/_generated_documents.graphql
- packages/sdk/src/_generated_documents.ts
- packages/sdk/src/_generated_sdk.ts
- packages/sdk/src/_tests/_generated.test.ts
Query `archivedTeams` has the same return type (`[Team!]!`) as the `nodes` field of `TeamConnection`. This confuses the `codegen-doc` plugin that would then print an incomplete `TeamConnection` fragment. This PR adds an exception to this mechanism for connection's fields.
It turns out it was already broken for the TemplateConnection (through query `templatesForIntegration`) but no tests actually attempt to traverse the nodes of connections. It's probably something we should consider adding to the suite of auto generated tests. `TeamConnection` leads to some build failures as it's being actively and explicitly used in the CLI importer and the README/bundle tests of the SDK.
> fix: do not re-use query for connection fields

- .changeset/tough-pants-cough.md
- packages/codegen-doc/src/constants.ts
- packages/sdk/src/_generated_documents.ts
- packages/sdk/src/_generated_sdk.ts
- packages/sdk/src/_tests/LinearSdk.test.ts
Resolves #427
The `metadata` field on `attachment` is always null, even on entities that do have some metadata. This is caused by an incorrect attempt at parsing `JSONObject` scalars, that fails silently. This actually affects all `JSONObject` fields on all models and has most likely always been broken. The test covering this is actually incorrect and is fixed in this PR.
Our schema defines two JSON scalar types, as follows:
```
"""
The `JSON` scalar type represents arbitrary values as *stringified* JSON
"""
scalar JSON
"""
The `JSONObject` scalar type represents arbitrary values as *embedded* JSON
"""
scalar JSONObject
```
The SDK is currently configured to treat both `JSON` and `JSONObject` in the same way through the following …
> fix: do not attempt to parse JSONObject scalars

- .changeset/_generated_schema_15229433.md
- .changeset/five-cycles-fly.md
- .changeset/quick-vans-compare.md
- packages/codegen-doc/src/fragment-visitor.ts
- packages/codegen-sdk/src/print-model.ts
- packages/codegen-test/src/print-test.ts
- packages/sdk/src/_generated_documents.graphql
- packages/sdk/src/_generated_documents.ts
- packages/sdk/src/_generated_sdk.ts
- packages/sdk/src/_tests/LinearSdk.test.ts
- packages/sdk/src/_tests/_generated.test.ts
- packages/sdk/src/schema.graphql
- packages/sdk/src/schema.json
We introduced a breaking change on Jan 5th when we allowed to query comments by hash ID and issueId. This schema change introduced a new arg type:
```
@Args() { id, issueId, hash }: CommentFindArgs
```
`CommentFindArgs` where all arguments are optional. There are validators at the API level to ensure validity of the passed arguments, but these do not have an impact on the schema.
This change means we now have a root query for an Entity that has 0 required arguments. This was a rather deep assumption in the SDK. The change broke some operation generation as well as test generation. 
The way tests for entities are working is as follows:
- We query all comments with `client.comments()` and keep the first one
- We then try to manually fetch this single comment by ID
- We keep this comment and …
> Add support for root query with all optional args

- .changeset/dull-hats-pump.md
- packages/import/src/importers/linearCsv/LinearCsvImporter.ts
The Linear CSV importer in the CLI importer relies on `csvtojson` to parse the CSV file. It's trying to infer the delimiter from the file but can somehow fail sometimes, throwing of the rest of the import.
As we know that Linear CSVs use `;` as a delimiter, we can hardcode it here.
> fix: specify CSV delimiter

- .changeset/few-timers-guess.md
- packages/import/src/importIssues.ts
Use of `.children()` on each label slows down import considerably when the workspace has many labels.
> fix: do not use .children call to check if label is a group

- .changeset/witty-rockets-teach.md
- packages/import/src/importIssues.ts
Use `issue.createdAt` to create issue with the appropriate creation date rather than the import date.
The description shows as updated now as the API created a new `DocumentContent` for this new `Issue`:
That's something we can look at addressing on the backend.
> feat: use issue.createdAt when creating issues

- .changeset/lovely-taxis-tease.md
- packages/import/src/importers/linearCsv/LinearCsvImporter.ts
This reverts commit 6e6639e where we tried to hardcode CSV delimiter value to overcome an issue with issue descriptions containing commas. Will revisit once we have identified the inconsistencies in the CSV file that led to this change.
> Revert "fix: specify CSV delimiter (#459)"

- .changeset/spicy-brooms-repair.md
- packages/sdk/src/_tests/LinearClient.test.ts
- packages/sdk/src/_tests/_mock.ts
- packages/sdk/src/client.ts
This PR adds a pagination helper to easily iterate over all pages of a `Connection` with the SDK.
The CLI importer lacks pagination on Users and Teams and will be fixed with this helper to properly iterate over these connections once released. 
In order to provide a unit test, which also acts as an usage example, it is required to modify the test server to allow to return different results for different queries (we need to return `hasNextPage: false` at some point for the test to complete). Approach for this is very simple for now: tests can supply a different response Mock, identified by a unique element from the query body.
> feat: add pagination helper

- .changeset/eighty-bees-tap.md
- packages/codegen-sdk/src/print-request.ts
- packages/sdk/src/_generated_sdk.ts
- packages/sdk/src/_tests/LinearClient.test.ts
- packages/sdk/src/client.ts
Follow-up on #486
In order for non-root queries to be properly bound during pagination calls, we need to move `paginate` into a parent class of `LinearClient`: `Request`. Otherwise, the `id` parameter is not bound and the query fails as `id` is always required.
As `Request` is a generated (printed) class, the pagination helper needs to be a generated function as well. A unit test is added to catch the missing ID parameter on the query.
Towards LIN-18253
> Move pagination helper into Request class

- .changeset/young-pianos-prove.md
- packages/import/src/importIssues.ts
This PR makes use of the newly introduced pagination helper in the SDK to properly paginate teams and users in CLI importer.
We will most likely need to rethink UX at some point if we need to support larger teams, as the current selection mode is a bit tedious if you have more than 25 teams
> fix: properly paginate teams and users in CLI importer

- .changeset/lucky-knives-sort.md
- packages/import/src/importIssues.ts
Depending on the import service, the issue's `assigneeId` can either be a user name or an email.
This PR changes the logic to pick `existingAssigneeId` from a match by email first, and then fall back on name match if there's no email match.
> fix: map assignees by email before name

- .changeset/old-moles-walk.md
- packages/import/package.json
- packages/import/src/importIssues.ts
- yarn.lock
When running a CLI import against a large workspace or with a large import dataset, it can be hard to know how much progress the importer has made. Often times, it just appears to hang. This PR adds indeterminate spinners to be used during API calls in preparation of the import, and a progress bar during issue import.
> feat: add spinners and progress bar to CLI importer

- .changeset/little-pots-flow.md
- packages/codegen-doc/src/constants.ts
- packages/codegen-doc/src/scalar.ts
- packages/sdk/scripts/update-scalars.ts
- packages/sdk/src/_generated_documents.ts
This will allow breaking change from 21.0.0 to be a drop-in replacement instead.
> fix: map DateTimeOrDuration scalar to string | Date type

- .changeset/many-yaks-hammer.md
- packages/import/src/importers/linearCsv/LinearCsvImporter.ts
We add these so that spreadsheets don't treat the value as a formula, but if we don't remove them before importing, then the created issue will be broken.
> fix: strip leading single quotes from Linear CSVs before importing

- .changeset/two-llamas-wonder.md
- packages/import/src/importIssues.ts
For now, we just hard-code the backoff here. In future (when we upgrade to Apollo Server 4), we can add the endpoint-specific rate limit to the response headers and use that.
After the first rate limited response, the CLI progress bar adjusts automatically. To test it easily, I set the rate limit locally to one issue per minute:
```
████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 10% | ETA: 2614s | 6/58
```
> feat(import): handle `issueCreate` rate limit

- .changeset/beige-shoes-pump.md
- packages/import/src/utils/replaceImages.ts
They already will be in a real Linear export, but we can also handle this directly when replacing image URLs. Consecutive newlines should be collapsed anyway, so this works for the already-on-its-own-line case too.
> fix(import): ensure that Markdown images are on their own line

- .changeset/loud-bobcats-grab.md
- packages/codegen-doc/src/print.ts
- packages/codegen-doc/src/types.ts
- packages/codegen-doc/src/utils.ts
- packages/codegen-sdk/src/model-visitor.ts
- packages/codegen-sdk/src/parse-operation.ts
- packages/codegen-sdk/src/print-connection.ts
- packages/codegen-sdk/src/print-model.ts
- packages/codegen-sdk/src/print-operation.ts
- packages/codegen-sdk/src/print.ts
- packages/codegen-sdk/src/types.ts
- packages/codegen-test/src/print-test.ts
- packages/import/src/importIssues.ts
- packages/import/src/importers/asanaCsv/AsanaCsvImporter.ts
- packages/import/src/importers/jiraCsv/JiraCsvImporter.ts
- packages/import/src/importers/linearCsv/LinearCsvImporter.ts
- packages/import/src/importers/shortcutCsv/ShortcutCsvImporter.ts
- packages/sdk/naming-override/index.js
- packages/sdk/scripts/update-scalars.ts
- packages/sdk/src/client.ts
- packages/sdk/src/error.ts
Adds support for `completedAt` date with supported importers: Asana, Linear and Shortcut.
Jira is left out as it currently doesn't import any dates. Jira CSVs do not come with a standard format and are dependent of the locale of the instance that generates them.
Github, Trello and Pivotal do not have or do not expose a concept of completion date through their API or CSV exports.
PR also includes linter updates that were not committed before.
> feat: add support for `completedAt` date in CLI importer

- README.md
- packages/sdk/README.md
The bootstrap step (probably lerna bootstrap) doesn't work, and isn't required.
> docs: Update "Get started"

- .changeset/quick-pants-attack.md
- packages/import/src/importIssues.ts
- packages/import/src/importers/jiraCsv/JiraCsvImporter.ts
- packages/import/src/importers/linearCsv/LinearCsvImporter.ts
- packages/import/src/importers/pivotalCsv/PivotalCsvImporter.ts
- packages/import/src/importers/shortcutCsv/ShortcutCsvImporter.ts
- packages/import/src/types.ts
- packages/import/src/utils/parseInt.ts
Add (actual) support for issue estimates in CLI importer. There were some pieces of estimate support in place but nothing end-to-end. 
- Linear: `Estimate` was defined in `LinearIssueType` but unused
- Jira: `Custom field (Story Points)` was defined but not used. Switched to looking for column `Custom field (Story point estimate)` which appears to be the standard when creating a new Jira Project.
- Shortcut: Using `estimate` field. 
- Pivotal: Uncommenting/fixing the existing estimate support (no context behind why it was as-is)
- Asana/Trello/Github: no concept of estimates
Resolves #606
> feat: add support for issue estimates in CLI importer

- packages/import/src/cli.ts
- packages/import/src/helpers/labelManager.ts
- packages/import/src/importIssues.ts
- packages/import/src/importers/asanaCsv/AsanaCsvImporter.ts
- packages/import/src/importers/gitlabCsv/GitlabCsvImporter.ts
- packages/import/src/importers/gitlabCsv/index.ts
- packages/import/src/importers/jiraCsv/JiraCsvImporter.ts
- packages/import/src/importers/linearCsv/LinearCsvImporter.ts
- packages/import/src/types.ts
This PR adds a GitLab CSV importer following the format documented here: https://docs.gitlab.com/ee/user/project/issues/csv_export.html#columns.
It also adds support for creating label groups that match a format of `<group name>/<label name>`
<hr />
Tested with the following CSV:
```
Title,Description,Issue ID,URL,State,Author,Author Username,Assignee,Assignee Username,Confidential,Locked,Due Date,Created At (UTC),Updated At (UTC),Closed At (UTC),Milestone,Weight,Labels,Time Estimate,Time Spent,Epic ID,Epic Title
Test issue,,1,https://gitlab.com/linear-development/test/-/issues/1,Open,Mufeez Amjad,mufeez-amjad,Mufeez Amjad,mufeez-amjad,No,No,2024-11-21,2024-11-07 04:02:12,2024-11-07 04:02:12,,,20,"Frameworks:TypeScript:Triage/P1,test/starter",0,0,,
Test issue …
```
> feat: add gitlab csv importer, support label groups

- .changeset/beige-pots-perform.md
- packages/import/src/importers/trelloJson/TrelloJsonImporter.ts
Looking at the sample json provided in #622, it looks like Trello might sometimes omit empty `labels` or `checklists` arrays.
I couldn't find any documentation about a potential change in the schema of Trello JSON exports, but it can't harm to protect against these as the Trello importer is currently poorly typed.
> fix: guard against missing empty arrays in trello json

- .changeset/friendly-ties-sleep.md
- packages/import/src/helpers/labelManager.ts
This PR updates the label manager logic to normalize label names where appropriate.
Note that we don't normalize when creating the label via the API – only how it's managed in the state.
> fix: normalize label names to prevent duplicates

- .changeset/_generated_dependencies.md
- package.json
- yarn.lock
Pins `@types/node` to `20.5.1` to fix broken `dependencies` action.
> fix: pin @types/node

- packages/codegen-doc/src/context-visitor.ts
This fixes one error (the `schema` job is [failing](https://github.com/linear/linear/actions/runs/12877733687/job/35902640454) because of it; PostNotification is being generated despite being internal).
CI passes on this PR, but I get this locally:
```
npx tsc --project tsconfig.check.json
packages/import/src/importIssues.ts:290:7 - error TS2345: Argument of type '{ teamId: string; projectId: string; title: string; description: string | undefined; priority: IssuePriority | undefined; labelIds: string[] | undefined; stateId: string | undefined; ... 4 more ...; estimate: number | undefined; }' is not assignable to parameter of type 'IssueCreateInput'.
Object literal may only specify known properties, and 'completedAt' does not exist in type 'IssueCreateInput'.
290       completedAt: …
```
> fix(sdk): ensure that internal interfaces are not generated

- .changeset/breezy-carpets-shave.md
- packages/import/src/importers/pivotalCsv/PivotalCsvImporter.ts
Pivotal uses dotted keys in CSV headers to represent multiple assignees:
```
| Owned By | Owned By.1 | Owned By.2 |
| -------- | ---------- | ---------- |
| John Doe | Jane Smith |            |
```
The default behavior for `csv2json` with the above input is to interpret this as JSON Path. It will create a field called `Owned By`, which is an array, and where elements `1` and `2` are set, and element at index `0` is undefined.
```
[undefined, "Jane Smith", ""]
```
Not only does this break the importer, as `assigneeId` is an array instead of the expected string, but we also lose the value of the first task owner.
Setting the `flatKeys` flag to `true` allows to bypass this behavior ([docs](https://www.npmjs.com/package/csvtojson#parameters)). The importer will only look at the first `Owned …
> fix: use flat keys to parse Pivotal CSVs

- packages/import/package.json
- packages/import/src/cli.ts
- packages/import/src/helpers/labelManager.ts
- packages/import/src/importIssues.ts
- packages/import/src/importers/trelloJson/TrelloJsonImporter.ts
- Fixes two cases where imports would fail due to label conflicts
1. Importing to a parent team when a sub-team has a label with the same name would fail
2. Importing a label where the team already has a `label` and `label (imported)` label would fail since we only rename it once
- Sorts the teams that are presented in the `linear-importer` CLI and show the parent team name for sub teams
- Add `cli:local` command that allows running the importer against local instance
> Rename labels on conflicts + order teams in importer cli

- README.md
- packages/sdk/README.md
This PR fixes the broken links pointing to the specific yml files.
There is a dot (`.`) after `/master` which led to the link broken
Remove the dots.
> fix(docs): broken links

- .changeset/cuddly-nights-leave.md
- packages/sdk/rollup.config.js
- packages/sdk/src/index.ts
- packages/sdk/src/index_umd.ts
The UMD module currently cannot be used in a browser directly as it imports nodejs's `crypto` module. This is used by `LinearWebhooks` to decode webhooks headers signatures when used in a nodejs context.
We could work with `crypto-browserify` and `node-browserify` polyfills to provide browser compatible version, but I'm not sure it's really worth it? The `LinearWebhooks` is meant to be used as an Express middleware, not in a browser environment. This PR provides a second entrypoint for rollup to build the UMD module without the `LinearWebhooks` export.
> fix: do not package `LinearWebhooks` in UMD module

- .changeset/_generated_schema_14662443.md
- .changeset/long-mails-hope.md
- package.json
- packages/sdk/Linear-Webhooks@current.graphql
- packages/sdk/src/_generated_documents.graphql
- packages/sdk/src/_generated_documents.ts
- packages/sdk/src/_generated_sdk.ts
- packages/sdk/src/schema.graphql
- packages/sdk/src/schema.json
Adds the last few types (audit entry, document, document content) and wrappers for entity webhooks and custom resource webhooks
> chore: add final webhook types

- .changeset/loose-cars-poke.md
- packages/sdk/src/types.ts
- packages/sdk/src/webhooks.ts
Adds ergonomics around parsing webhooks, especially given the awkwardness with union types which leads to `NotificationWebhookPayload` and `DataWebhookPayload` only living in `_generated_documents` and not `_generated_sdk`
> feat: helper to parse webhook payloads

- linear.code-workspace
Fixed config file. Otherwise it seems to love to complain about `suppressImplicitAnyIndexErrors` being removed in TS 5.0+
> chore: update workspace config to use workspace version of TypeScript

- .changeset/twenty-boxes-love.md
- packages/sdk/Linear-Webhooks@current.graphql
Adds in `AgentContext`-related webhook schema. 
_[Internal] These entities are currently not in use by production app._
> chore: update webhook schema

- .changeset/warm-dancers-laugh.md
- packages/sdk/src/graphql-client.ts
`isomorphic-unfetch` resolves & re-exports the global `fetch` at the time of import (if available). This means if you want to use something like MSW to intercept requests in testing, you need to get the order of imports/logic exactly right, or it will use the global `fetch` available at the time of import (& most likely make actual network requests)
Instead, when global fetch is available, we can use that directly (& allow the environment to inject a different implementation into the global scope, so things like MSW actually work)
Fixes LIN-38846
> Prefer current global fetch implementation over isomorphic-fetch if available

- .changeset/swift-doodles-beam.md
- package.json
- packages/sdk/src/webhooks.ts
> chore: fix return type for `parseData`

- .changeset/ninety-rocks-play.md
- packages/import/README.md
Update the CLI importer readme to mention GitLab CSVs. Also removes outdated todo list.
> chore: update import readme about gitlab

- .changeset/few-deer-design.md
- packages/sdk/src/index_umd.ts
I created two test projects, one with a browser env and one with a node.js env and testing this build and types work correctly in both. I also verified that before this change the node.js project was polluted with the global DOM types and it isn't anymore after this change.
> Remove explicit DOM typing

- .changeset/sharp-showers-mate.md
- .github/workflows/build.yaml
- packages/sdk/package.json
- packages/sdk/webhooks/package.json
Fixes https://github.com/linear/linear/issues/830, LIN-40569
This also adds `arethetypeswrong` (https://arethetypeswrong.github.io/) as a part of Build CI as an extra measure to ensure our exports are set up well. Demo of it failing before pushing the fix [here](https://github.com/linear/linear/actions/runs/16818931312/job/47641894084).
Locally I used [yalc](https://github.com/wclr/yalc) and tested `node myfile.mjs` importing from both `"@linear/sdk"` and `"@linear/sdk/webhooks"`, which I confirmed worked.
@itsmingjie would you be able to double-check your Bun/Express example against this and confirm it's still working?
> Fix import resolution from node ESM contexts

- linear.code-workspace
- Remove unneeded extension recommendation
- Remove unneeded GitLens configs (not a recommended extension, no reason to force workspace users to use these configs)
- Stop using deprecated `true` value for code actions (Cursor updated these values automatically upon save)
> chore: update VSCode workspace config

- .github/dependabot.yml
- .github/workflows/dependencies.yaml
This disables a scheduled dependency update workflow (leaving it available for on-demand runs if necessary), and adjusts Dependabot config for the repo to match the current Linear pattern used elsewhere.
> adjust dependency management tooling / config

- .changeset/rude-ants-look.md
- packages/import/src/importers/linearCsv/LinearCsvImporter.ts
Currently there is not an explicit requirement for the Labels field to be required in a Linear import, however there is no null (undefined) check for this.
This results in the following error when a Linear CSV with no labels is attempted to be imported:
```
TypeError: Cannot read properties of undefined (reading 'split')
at LinearCsvImporter.<anonymous> (/opt/homebrew/lib/node_modules/@linear/import/dist/cli.js:1288:41)
at Generator.next (<anonymous>)
at fulfilled (/opt/homebrew/lib/node_modules/@linear/import/dist/cli.js:72:58)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```
This change simply checks the presence of Labels before trying to split, if there are no labels in the CSV, then just make it an empty array.
> fix: null check for labels when importing linear CSV
